#!/bin/bash
Green_font_prefix="\033[32m"
Red_font_prefix="\033[31m"
Font_color_suffix="\033[0m"
Info="${Green_font_prefix}[ON]${Font_color_suffix}"
Error="${Red_font_prefix}[OFF]${Font_color_suffix}"

function check_auto_reboot {
    grep -c -E "^# BEGIN_REBOOT" /etc/crontab
}

function enable_auto_reboot {
    sed -i "/^# BEGIN_REBOOT/,/^# END_REBOOT/d" /etc/crontab
    cat << EOF >> /etc/crontab
# BEGIN_REBOOT
10 */12 * * * root fixcert
# END_REBOOT
EOF
    service cron restart
    echo -e "${Green_font_prefix}Auto-REBOOT Successfully Enabled${Font_color_suffix}"
}

function disable_auto_reboot {
    sed -i "/^# BEGIN_REBOOT/,/^# END_REBOOT/d" /etc/crontab
    echo -e "${Red_font_prefix}Auto-REBOOT Successfully Disabled${Font_color_suffix}"
}

function main_menu {
    clear
    echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
    local status=$(check_auto_reboot)
    if [[ "$status" -eq 1 ]]; then
        sts="${Info}"
    else
        sts="${Error}"
    fi
    echo -e "\033[1;93m│  AUTO REBOOT $sts          " | lolcat
    echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
    echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
    echo -e "\033[1;93m│  1. Enable AUTO REBOOT"
    echo -e "\033[1;93m│  2. Disable AUTO REBOOT"
    echo -e "\033[1;93m│  0. BACK TO EXIT MENU"
    echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
    echo -e ""
    read -p " Select menu : " opt
    case $opt in
        1 | 01)
            enable_auto_reboot
            ;;
        2 | 02)
            disable_auto_reboot
            ;;
        0 | 00)
            menu
            ;;
        *)
            exit
            ;;
    esac
    read -n 1 -s -r -p "Press any key to back on menu"
    main_menu
}

main_menu
