#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
NS=$(cat /root/nsdomain)
PUB=$(cat /etc/slowdns/server.pub)
domain=$(cat /etc/xray/domain)
CITY=$(cat /etc/xray/city)
# Getting
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
tr="$(cat ~/log-install.txt | grep -w "Trojan WS " | cut -d: -f2|sed 's/ //g')"
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${user_EXISTS} == '0' ]]; do
echo -e "\033[1;93m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e " CREATE TROJAN ACCOUNT          "
echo -e "\033[1;93m◇━━━━━━━━━━━━━━━━━◇\033[0m"

		read -rp "User: " -e user
		user_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

		if [[ ${user_EXISTS} == '1' ]]; then
clear
    user="TrojanPrem$(date +%s | sha256sum | base64 | head -c 8)"
			echo "Generated username: $user"
			CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l) # Check again
		fi
	done

uuid=$(cat /proc/sys/kernel/random/uuid)
read -p "Limit User (IP): " iplimit
read -p "Limit User (GB): " Quota
read -p "Expired (days): " masaaktif
read -p "ISI BUG (bug.com): " bug
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#trojanws$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#!# '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
if [ ! -e /etc/trojan ]; then
  mkdir -p /etc/trojan
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/trojan/ip
echo -e "$iplimit" > /etc/kyt/limit/trojan/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/trojan/${user}
fi
DATADB=$(cat /etc/trojan/.trojan.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/trojan/.trojan.db
fi
echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/trojan/.trojan.db
# Link Trojan Akun
trojanlink1="trojan://${uuid}@${bug}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}"
trojanlink="trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${bug}#${user}"
trojanlink2="trojan://${uuid}@${bug}:80?path=%2Ftrojan-ws&security=none&host=${domain}&type=ws#${user}"
systemctl restart xray > /dev/null 2>&1
systemctl restart nginx > /dev/null 2>&1
service cron restart > /dev/null 2>&1

cat >/var/www/html/trojan-$user.txt <<-END
---------------------------------------------------
# Format Trojan GO/WS
---------------------------------------------------
proxies:
  - name: Trojan-$user-GO/WS
    server: ${domain}
    port: 443
    type: trojan
    password: ${uuid}
    skip-cert-verify: true
    sni: ${bug}
    network: ws
    ws-opts:
      path: /trojan-ws
      headers:
        Host: ${domain}
    udp: true
---------------------------------------------------    
# Format Trojan gRPC
---------------------------------------------------
- name: Trojan-$user-gRPC
  type: trojan
  server: ${bug}
  port: 443
  password: ${uuid}
  udp: true
  sni: ${domain}
  skip-cert-verify: true
  network: grpc
  grpc-opts:
    grpc-service-name: trojan-grpc

◇━━━━━━━━━━━━━━━━━◇
   Trojan Account
◇━━━━━━━━━━━━━━━━━◇
Remarks          : ${user}
Domain           : ${domain}
User Quota       : ${Quota} GB
User Ip          : ${iplimit} IP
Port TLS         : 400-900
Port none TLS    : 80, 8080, 8081-9999
id               : ${uuid}
Xray Dns         : ${NS}
Pubkey           : ${PUB}
alterId          : 0
Security         : auto
Network          : ws
Path             : /Multi-Path
Dynamic          : https://$bug/path
ServiceName      : vmess-grpc
Location         : $CITY
=====================
 Link Akun Trojan                   
=====================
Link TLS: 
${trojanlink}
=====================
Link GRPC: 
${trojanlink1}
=====================


END

CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
◇━━━━━━━━━━━━━━━━━◇
   Trojan Account
◇━━━━━━━━━━━━━━━━━◇
Remarks          : ${user}
Domain           : ${domain}
User Quota       : ${Quota} GB
User Ip          : ${iplimit} IP
Port TLS         : 400-900
Port none TLS    : 80, 8080, 8081-9999
id               : ${uuid}
Xray Dns         : ${NS}
Pubkey           : ${PUB}
alterId          : 0
Security         : auto
Network          : ws
Path             : /Multi-Path
Dynamic          : https://$bug/path
ServiceName      : vmess-grpc
Location         : $CITY
◇━━━━━━━━━━━━━━━━━◇
 Link Akun Trojan                   
◇━━━━━━━━━━━━━━━━━◇
Link TLS: 
${trojanlink}
◇━━━━━━━━━━━━━━━━━◇
Link GRPC: 
${trojanlink1}
◇━━━━━━━━━━━━━━━━━◇
Format OpenClash : https://${domain}:81/trojan-$user.txt
◇━━━━━━━━━━━━━━━━━◇
Aktif Selama   : $masaaktif Hari
Dibuat Pada    : $tnggl
Berakhir Pada  : $expe
◇━━━━━━━━━━━━━━━━━◇
Allhamdulilah Trx Done
Terimakasih sudah order 🙏

📦Barang  : Trojan
✅️Konfig  : 
💸Nominal : 10 K
📆Tanggal : $tnggl
💳Payment : DANA
"
curl -s -X POST $URL --data-urlencode "chat_id=$CHATID" --data-urlencode "text=$TEXT" >/dev/null

clear
echo -e "\033[1;93m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e " Xray/Trojan Account "
echo -e "\033[1;93m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "Remarks          : ${user}"
echo -e "Domain           : ${domain}"
echo -e "User Quota       : ${Quota} GB"
echo -e "User Ip          : ${iplimit} IP"
echo -e "Port TLS         : 400-900"
echo -e "Port none TLS    : 80, 8080, 8081-9999"
echo -e "id               : ${uuid}"
echo -e "Xray Dns         : ${NS}"
echo -e "Pubkey           : ${PUB}"
echo -e "alterId          : 0"
echo -e "Security         : auto"
echo -e "Network          : ws"
echo -e "Path             : /Multi-Path"
echo -e "Dynamic          : https://bugmu.com/path"
echo -e "ServiceName      : vmess-grpc"
echo -e "Location         : $CITY"
echo -e "\033[0;34m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "Link TLS         : ${trojanlink}"
echo -e "\033[0;34m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "Link none TLS    : ${trojanlink2}"
echo -e "\033[0;34m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "Link GRPC        : ${trojanlink1}"
echo -e "\033[0;34m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "Format OpenClash : https://${domain}:81/vmess-$user.txt"
echo -e "\033[0;34m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "Aktif Selama     : $masaaktif Hari"
echo -e "Dibuat Pada      : $tnggl"
echo -e "Berakhir Pada    : $expe"
echo -e "\033[0;34m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo ""

