#!/bin/bash
# Generate UUID
uuid=$(cat /proc/sys/kernel/random/uuid)
# Ambil domain
domain=$(cat /etc/xray/domain)
user=$1
Quota=$2
iplimit=$3
masaaktif=$4
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`

# Tambahkan konfigurasi VLESS ke file Xray
sed -i '/#vless$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\#&& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json

# Generate JSON output
json_output=$(cat <<EOF
{
  "username": "$user",
  "domain": "$domain",
  "uuid": "$uuid",
  "quota": "$Quota GB",
  "ip_limit": "$iplimit IP",
  "expired": "$expe",
  "vless_tls_link": "vless://$uuid@$domain:443?security=tls&encryption=none&type=ws&path=%2Fvless&host=$domain&sni=$domain#$user",
  "vless_nontls_link": "vless://$uuid@$domain:80?security=none&encryption=none&type=ws&path=%2Fvless&host=$domain#$user",
  "vless_grpc_link": "vless://$uuid@$domain:443?security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=$domain#$user"
}
EOF
)

# Buat direktori jika belum ada
if [ ! -e /etc/vless ]; then
  mkdir -p /etc/vless
fi

# Atur batasan IP jika ada
if [[ $iplimit -gt 0 ]]; then
  mkdir -p /etc/kyt/limit/vless/ip
  echo -e "$iplimit" > /etc/kyt/limit/vless/ip/$user
else
  echo > /dev/null
fi

# Atur kuota jika ada
if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vless/${user}
fi

# Simpan data ke database
DATADB=$(cat /etc/vless/.vless.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/vless/.vless.db
fi
echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/vless/.vless.db

# Buat file teks untuk pengguna
cat >/var/www/html/vless-$user.txt <<-END
=====================
   Vless Account 
=====================
Remarks : ${user}
Domain : ${domain}
User Quota : ${Quota} GB
User Ip : ${iplimit} IP
Port TLS : 443
Port none TLS : 80
id : ${uuid}
Encryption : none
Security : auto
Network : ws
Path : /vless
ServiceName : vless-grpc
=====================
 Link Akun Vless                   
=====================
Link TLS: 
vless://$uuid@$domain:443?security=tls&encryption=none&type=ws&path=%2Fvless&host=$domain&sni=$domain#$user
=====================
Link none TLS: 
vless://$uuid@$domain:80?security=none&encryption=none&type=ws&path=%2Fvless&host=$domain#$user
=====================
Link GRPC: 
vless://$uuid@$domain:443?security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=$domain#$user
=====================
# Format Vless WS TLS
=====================
proxies:
  - name: Vless-$user-WS TLS
    server: ${domain}
    port: 443
    type: vless
    uuid: ${uuid}
    cipher: none
    tls: true
    skip-cert-verify: true
    servername: ${domain}
    network: ws
    ws-opts:
      path: /vless
      headers:
        Host: ${domain}
    udp: true
=====================
# Format Vless WS Non TLS
=====================
proxies:
  - name: Vless-$user-WS Non TLS
    server: ${domain}
    port: 80
    type: vless
    uuid: ${uuid}
    cipher: none
    tls: false
    skip-cert-verify: true
    servername: ${domain}
    network: ws
    ws-opts:
      path: /vless
      headers:
        Host: ${domain}
    udp: true
=====================
# Format Vless gRPC
=====================
proxies:
  - name: Vless-$user-gRPC (SNI)
    server: ${domain}
    port: 443
    type: vless
    uuid: ${uuid}
    cipher: none
    tls: true
    skip-cert-verify: true
    servername: ${domain}
    network: grpc
    grpc-opts:
      grpc-service-name: vless-grpc
    udp: true
END

# Cetak output JSON
echo "$json_output"

# Restart layanan
systemctl restart xray > /dev/null 2>&1
systemctl restart nginx > /dev/null 2>&1
service cron restart > /dev/null 2>&1