#!/bin/bash

# Generate Password
password=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)

# Ambil domain
domain=$(cat /etc/xray/domain)

# Input dari pengguna
user=$1
Quota=$2
iplimit=$3
masaaktif=$4
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`

# Cipher Shadowsocks
cipher="aes-128-gcm"

# Tanggal expired
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")

# Tambahkan konfigurasi Shadowsocks ke file Xray
sed -i '/#ssws$/a\#!! '"$user $exp"'\
},{"password": "'""$password""'","method": "'""$cipher""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#ssgrpc$/a\#&! '"$user $exp"'\
},{"password": "'""$password""'","method": "'""$cipher""'","email": "'""$user""'"' /etc/xray/config.json

# Generate Shadowsocks Base64
shadowsocks_base64=$(echo -n "$cipher:$uuid" | base64 -w 0)

# Buat direktori jika belum ada
if [ ! -e /etc/shadowsocks ]; then
  mkdir -p /etc/shadowsocks
fi

# Atur batasan IP jika ada
if [[ $iplimit -gt 0 ]]; then
  mkdir -p /etc/kyt/limit/shadowsocks/ip
  echo -e "$iplimit" > /etc/kyt/limit/shadowsocks/ip/$user
fi

# Atur kuota jika ada
if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/shadowsocks/${user}
fi

# Simpan data ke database
DATADB=$(cat /etc/shadowsocks/.shadowsocks.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/shadowsocks/.shadowsocks.db
fi
echo "### ${user} ${exp} ${password}" >>/etc/shadowsocks/.shadowsocks.db

# Generate Shadowsocks Links
sslinkws="ss://${shadowsocks_base64}@${domain}:443?path=/ss-ws&security=tls&encryption=none&type=ws#${user}"
nonsslinkws="ss://${shadowsocks_base64}@${bug}:80?path=/ss-ws&security=none&encryption=none&type=ws#${user}"
sslinkgrpc="ss://${shadowsocks_base64}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=ss-grpc&sni=${bug}#${user}"

# Generate JSON Output
json_output=$(cat <<EOF
{
  "username": "$user",
  "domain": "$domain",
  "password": "$password",
  "cipher": "$cipher",
  "quota": "$Quota GB",
  "ip_limit": "$iplimit IP",
  "expired": "$exp",
  "shadowsocks_ws_tls": "$sslinkws",
  "shadowsocks_ws_nontls": "$nonsslinkws",
  "shadowsocks_grpc": "$sslinkgrpc"
}
EOF
)

# Cetak output JSON
echo "$json_output"
# Restart layanan
systemctl restart xray > /dev/null 2>&1
systemctl restart nginx > /dev/null 2>&1
service cron restart > /dev/null 2>&1