#!/bin/bash
# ==========================================
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
clear
# ==========================================
function send_log() {
TIMES="10"
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT2="
<code>───────────────────────────</code>
                 ✨SUCCES DELET SSH✨
<code>───────────────────────────</code>
USERNAME       : <code>$Pengguna</code>
<code>───────────────────────────</code>
"
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT2&parse_mode=html" $URL >/dev/null
}
read -p "Ketik Usernamenya : " Pengguna

if getent passwd $Pengguna > /dev/null 2>&1; then
        userdel $Pengguna > /dev/null 2>&1
        sed -i "/^### $Pengguna/,/^},{/d" /etc/ssh/.ssh.db
        rm -f /etc/ssh/$Pengguna
        rm -f /etc/kyt/limit/ssh/ip/$Pengguna
	rm -f /var/www/html/ssh-$Pengguna.txt
        echo -e "User $Pengguna Berhasil Di Hapus Sayang."
        send_log
else
        echo -e "Failure: User $Pengguna Tidak Di Temukan."
fi

