#!/bin/bash
export HOME=/root
export TERM=xterm

red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
green() { echo -e "\\033[32;1m${*}\\033[0m"; }
red() { echo -e "\\033[31;1m${*}\\033[0m"; }
clear
function send_log() {
TIMES="10"
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT2="
<code>───────────────────────────</code>
      ✨SUCCES RENEW  VLESS✨
<code>───────────────────────────</code>
USERNAME       : <code>$user</code>
Expired On     : $exp4
Quota          : $Quota
Limit IP       : $iplim
<code>───────────────────────────</code>
"
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT2&parse_mode=html" $URL >/dev/null
}    
	read -rp "Input Username : " user
    read -p "Expired (days): " masaaktif
    read -p "Limit User (GB): " Quota
    read -p "Limit User (IP): " iplim
    exp=$(grep -wE "^#& $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
echo ${iplim} > /etc/kyt/limit/vless/ip/${user}
echo 0 > /etc/limit/vless/${user}
if [ ! -e /etc/vless/ ]; then
  mkdir -p /etc/vless/
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vless/${user}
fi
    now=$(date +%Y-%m-%d)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    exp3=$(($exp2 + $masaaktif))
    exp4=$(date -d "$exp3 days" +"%Y-%m-%d")
    sed -i "/^#& $user/c\#& $user $exp4" /etc/xray/config.json
    sed -i "/^#&& $user/c\#&& $user $exp4" /etc/xray/config.json
    sed -i "/^### $user/c\### $user $exp4" /root/akun/vless/.vless.conf
    sed -i "/^### $user/c\### $user $exp4" /etc/vless/.vless.db
    systemctl restart xray > /dev/null 2>&1
    send_log