#!/bin/bash
export HOME=/root
export TERM=xterm

# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
clear
function send_log() {
TIMES="10"
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT2="
<code>───────────────────────────</code>
        ✨SUCCES RENEW  SS✨
<code>───────────────────────────</code>
USERNAME       : <code>$user</code>
Expired On     : $exp4
<code>───────────────────────────</code>
"
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT2&parse_mode=html" $URL >/dev/null
}    
	read -rp "Input Username : " user
    read -p "Expired (days): " masaaktif
    read -p "Limit User (GB): " Quota
    read -p "Limit User (IP): " iplim
    exp=$(grep -wE "^#!! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    now=$(date +%Y-%m-%d)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    exp3=$(($exp2 + $masaaktif))
    exp4=$(date -d "$exp3 days" +%Y-%m-%d)
    echo $iplim > /etc/kyt/limit/shadowsocks/ip/${user}
echo 0 > /etc/limit/shadowsocks/${user}
if [ ! -e /etc/shadowsocks/ ]; then
  mkdir -p /etc/shadowsocks/
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/shadowsocks/${user}
fi
    sed -i "/^#!! $user/c\#!! $user $exp4" /etc/xray/config.json
    sed -i "/^#&! $user/c\#&! $user $exp4" /etc/xray/config.json
    sed -i "/^### $user/c\### $user $exp4" /root/akun/shadowsocks/.shadowsocks.conf
    sed -i "/^### $user/c\### $user $exp4" /etc/shadowsocks/.shadowsocks.db
    systemctl restart xray > /dev/null 2>&1
    send_log